

name: Maven Build Automation for Project (Pipeline)

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Maven Clean Install
        run: mvn clean install
      - name: Maven Test
        run: mvn test
      - name: Maven Javadoc
        run : mvn javadoc:javadoc
